//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetWithAngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public string monthAssigned { get; set; }
    
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
